name: CI

on:
  push:
    branches-ignore:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.7
        with:
          args: --config codeQuality/detekt.yml
